version: "3"
services:
  api:
    build: ./
    command: yarn run watch
    env_file:
     - ./.env
    volumes:
      - ./:/usr/src/app
    ports:
    - "4200:4200"
    depends_on:
    - db
  db:
   image: mongo:latest
   container_name: mongo
   ports:
    - "27017:27017"
   volumes:
    - ./data:/data/db